In [164]:
#Name : Ram Darekar
#Roll No : 114
#Div : B

import numpy as np
import pandas as pd

In [165]:
s=pd.Series([100,200,300,400,500],index=['a','b','c','d','e'])

print("pandas Series")
print(s)


print("Accessing elements by indesx:", s['e'])

pandas Series
a    100
b    200
c    300
d    400
e    500
dtype: int64
Accessing elements by indesx: 500

In [166]:
print("printing the type",type(s))

printing the type <class 'pandas.core.series.Series'>

In [167]:
data={
    'Name':['Ram','Abhi','Pajju','kuldeep'],
     'Age':[21,22,19,18],
     'cgpa':[8.5,9.0,7.5,8.0],
     'marks':[85,90,75,80]  
    
     }  


df=pd.DataFrame(data)
print("\nDataframe\n")
print(df)
print("\nAccessing elements by index:")    
print(df['Name'])

Dataframe

      Name  Age  cgpa  marks
0      Ram   21   8.5     85
1     Abhi   22   9.0     90
2    Pajju   19   7.5     75
3  kuldeep   18   8.0     80

Accessing elements by index:
0        Ram
1       Abhi
2      Pajju
3    kuldeep
Name: Name, dtype: object

In [168]:
print(df['cgpa'])     # accessing a specific column
print(df.iloc[2])    # accessing a specific row
df.iloc[1:3]            # accessing a range of rows

0    8.5
1    9.0
2    7.5
3    8.0
Name: cgpa, dtype: float64
Name     Pajju
Age         19
cgpa       7.5
marks       75
Name: 2, dtype: object

    Name  Age  cgpa  marks
1   Abhi   22   9.0     90
2  Pajju   19   7.5     75

In [169]:
print("printing the type:",type(df))    # DataFrame is a 2D labeled data structure

printing the type: <class 'pandas.core.frame.DataFrame'>

In [170]:
data=pd.read_csv('college_student_placement_dataset.csv')  # reading the dataset

In [171]:
data.info()  # information about the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   College_ID              10000 non-null  object
 1   IQ                      10000 non-null  int64
 2   Prev_Sem_Result         10000 non-null  float64
 3   CGPA                    10000 non-null  float64
 4   Academic_Performance    10000 non-null  int64
 5   Internship_Experience   10000 non-null  object
 6   Extra_Curricular_Score  10000 non-null  int64
 7   Communication_Skills    10000 non-null  int64
 8   Projects_Completed      10000 non-null  int64
 9   Placement               10000 non-null  object
dtypes: float64(2), int64(5), object(3)
memory usage: 781.4+ KB

In [172]:
data.describe()      # statistical summary of the dataset

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Extra_Curricular_Score,Communication_Skills,Projects_Completed
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,99.471800,7.535673,7.532379,5.546400,4.970900,5.561800,2.513400
std,15.053101,1.447519,1.470141,2.873477,3.160103,2.900866,1.715959
min,41.000000,5.000000,4.540000,1.000000,0.000000,1.000000,0.000000
25%,89.000000,6.290000,6.290000,3.000000,2.000000,3.000000,1.000000
50%,99.000000,7.560000,7.550000,6.000000,5.000000,6.000000,3.000000
75%,110.000000,8.790000,8.770000,8.000000,8.000000,8.000000,4.000000
max,158.000000,10.000000,10.460000,10.000000,10.000000,10.000000,5.000000

In [173]:
data.head()        # first 5 rows

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,CLG0030,107,6.61,6.28,8,No,8,8,4,No
1,CLG0061,97,5.52,5.37,8,No,7,8,0,No
2,CLG0036,109,5.36,5.83,9,No,3,1,1,No
3,CLG0055,122,5.47,5.75,6,Yes,1,6,1,No
4,CLG0004,96,7.91,7.69,7,No,8,10,2,No

In [174]:
data.tail()        # last 5 rows

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
9995,CLG0021,119,8.41,8.29,4,No,1,8,0,Yes
9996,CLG0098,70,9.25,9.34,7,No,0,7,2,No
9997,CLG0066,89,6.08,6.25,3,Yes,3,9,5,No
9998,CLG0045,107,8.77,8.92,3,No,7,5,1,No
9999,CLG0060,109,9.41,9.77,8,No,3,5,5,No

In [175]:
data.shape         # (rows, columns)

(10000, 10)

In [176]:
data.dtypes        # data types of each column

College_ID                 object
IQ                          int64
Prev_Sem_Result           float64
CGPA                      float64
Academic_Performance        int64
Internship_Experience      object
Extra_Curricular_Score      int64
Communication_Skills        int64
Projects_Completed          int64
Placement                  object
dtype: object

In [177]:
data.columns       # list of column names

Index(['College_ID', 'IQ', 'Prev_Sem_Result', 'CGPA', 'Academic_Performance',
       'Internship_Experience', 'Extra_Curricular_Score',
       'Communication_Skills', 'Projects_Completed', 'Placement'],
      dtype='object')

In [178]:
data.index         # row index

RangeIndex(start=0, stop=10000, step=1)

In [179]:
data['Academic_Performance']   # accessing a specific column

0       8
1       8
2       9
3       6
4       7
       ..
9995    4
9996    7
9997    3
9998    3
9999    8
Name: Academic_Performance, Length: 10000, dtype: int64

In [180]:
data['IQ'].mean()  # mean of IQ column

np.float64(99.4718)

In [181]:
data['Internship_Experience'].value_counts()  # count of unique values in Internship_Experience column

Internship_Experience
No     6036
Yes    3964
Name: count, dtype: int64

In [182]:
data['Communication_Skills'].max()  # maximum Communication_Skills value

np.int64(10)

In [183]:
data['Communication_Skills'].min()  # minimum Communication_Skills value

np.int64(1)

In [184]:
data['Communication_Skills'].sum()  # sum of Communication_Skills values

np.int64(55618)

In [185]:
data['Communication_Skills'].median()   # median of Communication_Skills values

np.float64(6.0)